# Generated by Django 4.2.16 on 2024-11-28 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only alphanumeric characters', regex='^[a-zA-Z0-9]*$')])),
                ('email', models.EmailField(max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('online', models.BooleanField(default=False)),
                ('intra_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
