# Generated by Django 4.2.16 on 2025-01-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelationship',
            name='type',
            field=models.IntegerField(unique=True),
        ),
    ]
