# Generated by Django 4.2.16 on 2024-11-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
