# Generated by Django 4.2.16 on 2025-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ingame',
            field=models.BooleanField(default=False),
        ),
    ]
