# Generated by Django 4.2.16 on 2024-11-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_tfa_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tfa_enabled',
            new_name='mfa_enabled',
        ),
    ]
