# Generated by Django 4.2.16 on 2024-12-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intra_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intra_user',
        ),
    ]
