# Generated by Django 4.2.16 on 2024-12-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_intra_uid_remove_user_intra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_totp_secret',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
