# Generated by Django 4.2.16 on 2025-01-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchmakingQueue',
        ),
    ]
