# Generated by Django 4.2.16 on 2025-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmakingqueue',
            name='game_type',
            field=models.CharField(default='pong', max_length=15),
        ),
    ]
