# Generated by Django 5.1.3 on 2024-12-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
