# Generated by Django 4.2.16 on 2025-01-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='forfeit',
            field=models.BooleanField(default=False),
        ),
    ]
