# Generated by Django 5.1.3 on 2024-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_delete_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_type',
            field=models.CharField(default='pong', max_length=10),
        ),
        migrations.AddField(
            model_name='matchmakingqueue',
            name='game_type',
            field=models.CharField(default='pong', max_length=10),
        ),
    ]
