# Generated by Django 4.2.16 on 2025-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_matchmakingqueue_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.CharField(default='pong', max_length=15),
        ),
    ]
